name: star-hunters # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Star Hunters Saga
summary: Hunt riches among the cosmos.
description: Unearth cosmic riches and dodge alien threats as you explore the vastness of space.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  star-hunters:
    command: bin/star-hunters-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  star-hunters:
    plugin: dump
    source: .
    organize:
      star-hunters-bin: bin/
